trigger:
- master
- test
variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)
  #GIT_COMMIT_SHORT: git rev-parse --short HEAD

pool:
  vmImage: 'ubuntu-latest'
  #name: Default 
  #demands: Agent.Name -equals linux
steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here|
      short_hash=`git rev-parse --short=7 HEAD`
      #sudo echo -e "[default]\naws_access_key_id = AKIAQ3EGSYUXRRFQLS52 \naws_secret_access_key = p/OjVvCOkSHMm1JdnxkrtCqw3wqZc88b8YrBQI2G" > /home/ubuntu/.aws/credentials
      #sudo echo -e "[default]\nregion = eu-west-1" > /home/ubuntu/.aws/config
      #aws s3 cp /home/ubuntu/myagent/_work/1/s/target/spring-boot-web.jar s3://azurepipeline-bucket/spring-boot-web-$short_hash.jar
- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: dockerhub
- task: Docker@2
  inputs:
    Dockerfile: '**/Dockerfile'
    command: 'buildAndPush'
    tags: '$(Build.BuildId)'
    containerRegistry: dockerhub
    repository: webapp


