trigger:
- master
- test
variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)

pool:
  vmImage: "ubuntu-latest"
steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'Sonar'
    scannerMode: 'Other'
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'


