trigger:
- master

pool:
  name: Default
  demands:
   - agent.name -equals ip-172-31-90-206
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'

- task: ShellScript@1
  inputs:
    scriptPath: aws.sh