trigger:
- master

pool:
  vmImage: "ubuntu-latest"
steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'

- task: Docker@2
  inputs:
    containerRegistry: 'Docker'
    repository: 'rvsivadocker/azure-devops'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
