trigger:
- master
- test
variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)

pool:
  name: Default 
  demands: Agent.Name -equals linux
steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      sudo mkdir /home/ubuntu/.aws
      sudo echo -e "[default]\naws_access_key_id = AKIAQ3EGSYUXRRFQLS52 \naws_secret_access_key = p/OjVvCOkSHMm1JdnxkrtCqw3wqZc88b8YrBQI2G" > /home/ubuntu/.aws/credentials
      sudo echo -e "[default]\nregion = eu-west-1" > /home/ubuntu/.aws/config
      aws s3 cp /home/vsts/work/1/s/target/spring-boot-web.jar s3://azurepipeline-bucket/spring-boot-web.jar


