trigger:
- master
- test
variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)

pool:
  vmImage: "ubuntu-latest"
steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      aws configure set aws_access_key_id "AKIAQ3EGSYUXRRFQLS52" --profile user2 && aws configure set aws_secret_access_key "p/OjVvCOkSHMm1JdnxkrtCqw3wqZc88b8YrBQI2G" --profile user2 && aws configure set region "eu-west-1" --profile user2 && aws configure set output "text" --profile user2
      /home/ubuntu/1/s/target/spring-boot-web.jar s3://azurepipeline-bucket/spring-boot-web.jar


